USE SCHOOL;

SELECT XH,XM
FROM S
WHERE NOT EXISTS (
    SELECT KH
    FROM E
    WHERE XH = '1106'
    AND NOT EXISTS (
        SELECT *
        FROM E AS X
        WHERE S.XH = X.XH
        AND E.KH = X.KH));

SELECT KH,S.XH,XM,ZPCJ
FROM S,E
WHERE S.XH = E.XH
AND E.ZPCJ = (
    SELECT MAX(X.ZPCJ)
    FROM E AS X
    WHERE X.KH = E.KH)

SELECT E.XH,XM,AVG(ZPCJ),GS
FROM S,E,(
    SELECT E.XH,COUNT(E.KH) AS GS
    FROM E,S,(
        SELECT KH,AVG(ZPCJ) AS CJ
        FROM E GROUP BY KH)
    AS Q
    WHERE S.XH=E.XH
    AND E.KH = Q.KH
    AND E.ZPCJ > Q.CJ
    GROUP BY XH)
AS R
WHERE S.XH=E.XH
AND R.XH=E.XH
GROUP BY XH
HAVING(COUNT(KH) = GS)
ORDER BY(S.CSRQ);

CREATE VIEW CJ
AS SELECT S.XH,XM,XB,SJHM,KH,ZPCJ
    FROM S,E
    WHERE S.XH = E.XH
    AND ZPCJ < 60;

INSERT INTO E
SELECT DISTINCT S.XH,O.XQ,O.KH,O.GH,null,null,null
FROM S,O
WHERE NOT EXISTS (
    SELECT *
    FROM E
    WHERE E.XH = S.XH
    AND E.KH = O.KH);

SELECT XH,XM
FROM S
WHERE XB = 1
AND CSRQ < ALL(
    SELECT CSRQ
    FROM S
    WHERE XB = 0);

UPDATE E SET PSCJ = PSCJ * 1.04 WHERE KH = '08305001' AND PSCJ > 75;
UPDATE E SET PSCJ = PSCJ * 1.05 WHERE KH = '08305001' AND PSCJ <= 75;

DELETE FROM D
WHERE YXH NOT IN (
    SELECT YXH
    FROM C,O
    WHERE C.KH = O.KH);

SELECT E.KH,
    (SELECT COUNT(DISTINCT E0.XH)
    FROM E AS E0
    WHERE E0.ZPCJ >= 90
    AND E0.KH = E.KH)
AS A,
    (SELECT COUNT(DISTINCT E1.XH)
    FROM E AS E1
    WHERE E1.ZPCJ < 90
    AND E1.ZPCJ >= 80
    AND E1.KH = E.KH)
AS B,
    (SELECT COUNT(DISTINCT E2.XH)
    FROM E AS E2
    WHERE E2.ZPCJ < 80
    AND E2.ZPCJ >= 70
    AND E2.KH = E.KH)
AS C,
    (SELECT COUNT(DISTINCT E3.XH)
    FROM E AS E3
    WHERE E3.ZPCJ < 70
    AND  E3.ZPCJ >= 60
    AND E3.KH = E.KH)
AS D,
    (SELECT COUNT(DISTINCT E4.XH)
    FROM E AS E4
    WHERE E4.ZPCJ < 60
    AND E4.KH = E.KH)
AS F
FROM E
GROUP BY E.KH;
