USE SCHOOL;

SELECT XH, XM 
FROM S 
WHERE DATE_SUB(CSRQ, INTERVAL 1 YEAR) > 20 
AND XH LIKE '11%' 
AND XB = 1;

SELECT KH 
FROM O 
WHERE KH NOT IN (
    SELECT KH 
    FROM E,S 
    WHERE E.XH = S.XH 
    AND S.XM = '刘晓明');

SELECT XQ, KH, SKSJ 
FROM O, T 
WHERE O.GH = T.GH 
AND T.XM = '马小红';

SELECT E.KH, C.KM, T.XM 
FROM E, C, T, S, D WHERE 
E.XH = S.XH 
AND E.KH = C.KH 
AND E.GH = T.GH 
AND S.YXH = D.YXH 
AND S.XB = 1 
AND MC = '计算机学院'
AND E.ZPCJ >= 60 
AND T.XL = '教授' 
ORDER BY 3, 1 DESC;

SELECT XH, XM 
FROM S 
WHERE XH > (
    SELECT XH 
    FROM S 
    WHERE XM = '张颖') 
AND CSRQ > (
    SELECT CSRQ 
    FROM S 
    WHERE XM = '张颖');

SELECT DISTINCT S.XH, S.XM 
FROM S, E AS X, E AS Y 
WHERE S.XH = X.XH 
AND S.XH = Y.XH 
AND X.KH = '08305001' 
AND Y.KH = '08305002';

SELECT S.XH, COUNT(DISTINCT KH) 
FROM S LEFT OUTER JOIN E ON (E.XH = S.XH) 
GROUP BY S.XH;

SELECT XH, XM 
FROM S 
WHERE NOT EXISTS (
    SELECT KH 
    FROM O 
    WHERE NOT EXISTS(
        SELECT * 
        FROM E 
        WHERE E.XH = S.XH 
        AND E.KH = O.KH));



